// Code generated by "stringer -type=stat -linecomment"; DO NOT EDIT.

package pokeapi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stat_Undefined-0]
	_ = x[stat_HP-1]
	_ = x[stat_Atk-2]
	_ = x[stat_Def-3]
	_ = x[stat_SpAtk-4]
	_ = x[stat_SpDef-5]
	_ = x[stat_Spd-6]
}

const _stat_name = "undefinedhpattackdefensespecial-attackspecial-defensespeed"

var _stat_index = [...]uint8{0, 9, 11, 17, 24, 38, 53, 58}

func (i stat) String() string {
	if i >= stat(len(_stat_index)-1) {
		return "stat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _stat_name[_stat_index[i]:_stat_index[i+1]]
}
