// Code generated by "stringer -type=LearnMethod -linecomment"; DO NOT EDIT.

package pkmn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LearnMethod_Undefined-0]
	_ = x[LearnMethod_LevelUp-1]
	_ = x[LearnMethod_Egg-2]
	_ = x[LearnMethod_Tutor-3]
	_ = x[LearnMethod_Machine-4]
	_ = x[LearnMethod_StadiumSurfingPikachu-5]
	_ = x[LearnMethod_LightBallEgg-6]
	_ = x[LearnMethod_ColosseumPurification-7]
	_ = x[LearnMethod_XDShadow-8]
	_ = x[LearnMethod_XDPurification-9]
	_ = x[LearnMethod_FormChange-10]
	_ = x[LearnMethod_ZygardeCube-11]
}

const _LearnMethod_name = "undefinedlevel-upeggtutormachinestadium-surfing-pikachulight-ball-eggcolosseum-purificationxd-shadowxd-purificationform-changezygarde-cube"

var _LearnMethod_index = [...]uint8{0, 9, 17, 20, 25, 32, 55, 69, 91, 100, 115, 126, 138}

func (i LearnMethod) String() string {
	if i >= LearnMethod(len(_LearnMethod_index)-1) {
		return "LearnMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LearnMethod_name[_LearnMethod_index[i]:_LearnMethod_index[i+1]]
}
