# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Display Go version
      run: go version

    - name: Build
      run: make build

    - name: Test
      # Setting bash explicitly uses `set -o pipefail` to execute the step. This ensures that if any
      # subcommand in the pipe fails, it fails immediately
      shell: bash
      # NOTE: I'm sorry for this multi-line command, but I'd like the test output visible in the
      # GH actions output
      run: >
          make -s test addopts=-json
          | tee test-results.json
          | jq '. | select(. | has("Output")) | .Output'
          | jq --slurp -r '. | join("")'

    - name: Lint
      run: make check

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.go-version }}
        path: test-results.json
